# Generated by Django 5.1.5 on 2025-02-04 10:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='infos/')),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('adress', models.TextField()),
                ('NativePlace', models.CharField(max_length=100)),
                ('occuppation', models.CharField(max_length=100)),
                ('study', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('addDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
